### ISSUE TITLE
CDN for Less

### ISSUE THREAD

**Issue by matthew-dean** [less/less-meta#19]
In the documentation, there are links for a Cloudflare CDN-hosted Less file. However, that's a piece of releasing that I don't know how to do. Does anyone know how to update Cloudflare with a new Less.js release?

**Comment by seven-phases-max** [comment]
It's updated automatically (https://github.com/cdnjs/cdnjs/pull/4009).

**Comment by matthew-dean** [comment]
Hmm...  currently `package.json` is missing those keys that were added with that change.

**Comment by seven-phases-max** [comment]
The `package.json` is in the `cdnjs` repo not part of the Less repo.
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/less.js/package.json.

**Comment by matthew-dean** [comment]
Oh. Ha. I clearly wasn't paying attention.
