### ISSUE TITLE
Less naming guideline for the docs ("Less", "LESS" or "Less.fortran")

### ISSUE THREAD

**Issue by seven-phases-max** [less/less-meta#24]
(reserved for final decision)

**Comment by seven-phases-max** [comment]
This is a proposal of naming guidelines for the docs README (to replace current [Capitalizing "Less"](https://github.com/less/less-docs/blob/master/README.md#capitalizing-less) section). Inspired by the discussion at https://github.com/less/less-docs/issues/443.

---
### *Text*:

The name of the project is *Less*. Anywhere in the docs, *Less* means both the language and its official, reference implementation.
The *less.js* form is normally to be used only to specify either of:
* the browser script file name
* the particular GitHub repository (where all of the development takes place)

Examples:
- "Less language", "Less library", "Less API", "Less plugin", "Using Less" etc.
- "Fork [less/less.js](https://github.com/less/less.js) repository" (synonyms: "Less Repository", "Main Repository" etc.)
- "Make sure to include your stylesheets before the [less.js](https://github.com/less/less.js/blob/v2.7.2/dist) script"

---

Purpose:
--------
The primarily purpose of the proposal is to:
1. Provide a simple and straight-forward "no-brainer" naming convention.
2. Accept the lie of the land and suggest just a little more consistency there. 
    (*Not* to develop a new guidelines covering all potential future developments and/or past, present or future edge-cases).

Rationale:
-----------
* There's no separate "Less Language" and "JavaScript Less Implementation" projects.
The "Language <-> ReferenceImplementation" thing is a monolith.
<sub>Let's be realistic, *if* a more active and more advanced "Less.WhateverLanguage/Platform" project comes in, all development including the language will move there. Thus this new implementation simply becomes the new "Less".</sub>

* When forming your opinion make sure you're not trapped by the recent trend of naming everything as "Anything.js".
<sub>Their names is *their* business but *this* thing is named "Less". It [was not](https://github.com/less/less.ruby/tree/v0.5.2#less) "LESS.Ruby" then and should not be "Less.js" now.</sub>

* We don't have (nor want to have) naming like:
  - `less.js-node`,
  - `gulp-less.js`,
  - `less.js-plugin-happiness`
  - `npm install less.js`
  - `less.js-docs`
  - and finally `less.js.min.js`
.

 * *Q.* Isn't *Less* too ambiguous? There're too many *less* things out there.
  *A.* Not at lesscss.org and less/less.js 
  <sub>Feel free to use "less.js"/"Less.js" out there ([for example](https://gitter.im/less/less.js)) to resolve any ambiguity. But at the docs it's just redundant and even more ambiguous: "Did he mean the browser script?".</sub>

**Comment by seven-phases-max** [comment]
This guideline should obviously apply to [less/less.js](https://github.com/less/less.js) texts as well (where applicable).
E.g. its [README](https://github.com/less/less.js#lessjs) header:
>### Less.js
>This is the JavaScript, official, stable version of Less.

to be replaced with (something like):
>### Less
>The official, JavaScript implementation.

etc.

**Comment by matthew-dean** [comment]
Yep. Simpler is better. I noticed recently that Sass doesn't really distinguish between the language and the compiler. Sass is the language, and it has an official compiler. (Well, two, now, I think. On the other hand, Sass does have a little bit of confusion around there being Sass, which has two language variants: Sass and SCSS, which fortunately, Less does not have.)

Sorry if I added to that complexity. Language is a balance between clarity and simplicity. One word / capitalization for Less is fine, and probably best.

Is it worth, then, renaming the repo `less/less`? I'm not sure why we settled on `Less.js`, except to specify it was the compiler. But yeah, that's probably overkill. Renaming might help eliminate the idea that the project is "Less.js", which it isn't.

**Comment by matthew-dean** [comment]
@seven-phases-max Are you updating both 2.x and 3.x docs? or Just 3.x?

**Comment by matthew-dean** [comment]
@seven-phases-max By the way, the way I was doing updates was:

1. Updating and then generating 2.x docs.
2. Updating and then generating 3.x docs without deleting 2.x docs. (I removed the step in 3.x docs where it was wiping the built directory.)
3. Deploying the web pages to Github.

**Comment by seven-phases-max** [comment]
>Are you updating both 2.x and 3.x docs?

Both. (Where applicable at least - some 2.x changes I made can't fit into 3.x and/or assume their own major edits anyway. Also I did not deploy 3.x version for some really minor changes).

**Comment by rjgotten** [comment]
My $ 0.02: Less is Less, and where there is ambiguity in the meaning clarify further and be exact. 

E.g.
* "the Less language";
* "the Less compiler API for browsers";
* "the Less compiler API for Node.js"; or
* "the Less commandline compiler for Node.js"

Actually; of those the last one is the only odd one out, and that's because you've already opted into `lessc` ("Less compiler" or "Less commandline", I assume?) as the NPM package name.

**Comment by seven-phases-max** [comment]
>because you've already opted into lessc ("Less compiler" or "Less commandline", I assume?) as the NPM package name.

Here we'll get too deep into linguistic exercises I guess, but in my realm, if we go strict, "Less compiler" != `lessc`. 

Remember, by `npm install less` we install the whole library (and the library is the real "Less compiler" there), while a command line interface script for that library (i.e. `less-cli`, aka `lessc`) -  is just a thin wrapper for the library and only a tiny part of that package (sure, in general it's nothing wrong in referring to `lessc` as a "Less compiler" too - it's just a useful and friendly simplification for every-day usage. After all, aren't `gulp-less` and `grunt-contrib-less` "Less compilers" too? ;). 

Related example from recent SO posts (just for inspiration): http://stackoverflow.com/questions/43812427/how-npm-plugins-for-task-managers-are-made

**Comment by seven-phases-max** [comment]
So, if there's no objections (I guess I'll wait for a week or two just in case) I'll put that into the readme. Sure feel free to make any corrections (right by editing the proposal post if you can).

**Comment by seven-phases-max** [comment]
Done.
