### ISSUE TITLE
Is there any (simple?) way to edit GitHub posts programmatically?

### ISSUE THREAD

**Issue by seven-phases-max** [less/less-meta#8]
I'm asking because it looks like sooner we (probably) won't have http://stackoverflow.com/questions/tagged/less anymore (there's quite entertaning in its absurdity disscussion [here](http://meta.stackoverflow.com/questions/293664/we-need-less-no-more)). So considering I posted several (20-30?) links to http://stackoverflow.com/questions/tagged/less in less.js/less-docs issues here and there, is there anyway I can change/fix them programmatically?

**Comment by matthew-dean** [comment]
That thread is kind of a crazy. I think tagging things with "lesscss" is okay, but yeah, I understand that fucks things up for where we have them tagged.

**Comment by seven-phases-max** [comment]
Ok, the threat seems to go away (this time :). So I'm closing this for now.
